### ISSUE TITLE
using weaveworks/net-plugin in swarm mode

### ISSUE THREAD

**Issue by aaami1ster** [dashersw/cote#146]
I am using docker in swarm  mode. I use weaveworks/net-plugin and enable multicast as follows
I did the following step to deply my service in swarm mode with cote and weaveworks/net-plugin. 

1. step one: i run the following commands in each node

```
docker plugin install weaveworks/net-plugin:latest_release &&
docker plugin disable weaveworks/net-plugin:latest_release && 
docker plugin set weaveworks/net-plugin:latest_release WEAVE_MULTICAST=1 &&
docker plugin enable weaveworks/net-plugin:latest_release
```

1. step two: I ran my compose file this my file

```
version: '3'

networks:
  cote:
    # driver: "overlay" 
    driver: "weaveworks/net-plugin:latest_release"
services:
  api-service:
    image: aaami1ster/taxi:base
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - TZ=Africa/Cairo
    networks:
      - cote
    command: node api-service/bin/www
    ports:
      - "3100:3100"
my-service:
    image: aaami1ster/taxi:base
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - TZ=Africa/Cairo
    networks:
      - cote
    command: node my-service/app.js
```
I enable multicast, but still not work. what am I missing?????
