### ISSUE TITLE
Example for several docker compose

### ISSUE THREAD

**Issue by JeanDenisVIDOT** [dashersw/cote#92]
Hello,
I'm trying to test the library and I got a problem : 
I'm using several docker-compose.yaml (actually 2): 
I created a docker network as the following : 

```bash
docker network create cote_test
```
and my docker compose files look like that :

```
version: '3'

services:
  db:
    restart: 'on-failure'
    image: 'mongo'
    volumes:
      - './data/db:/data/db'
    networks:
      - 'db'
  service:
    restart: 'on-failure'
    depends_on:
      - 'db'
    build: './docker/cote-service'
    volumes:
      - './www:/app'
    networks:
      - 'db'

networks:
  default:
    external:
      name: 'cote_test'
  db:
```
But when I start them, the send from the requester is not received by the responder...
Someone does not what I'm doing wrong ?
